models/Candidate.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use app\models\CandidateTag;

/**
 * This is the model class for table "candidate".
 *
 * @property int $id
 * @property string $name ФИО
 * @property string $email Email
 * @property string $phone Телефон
 * @property string $city Город
 * @property string $comment Комментарий
 * @property string $education Образование
 * @property string $work_experience Опыт работы
 * @property string $age Возраст
 * @property string $languages Знание языков
 * @property string $additional Дополнительная информация
 * @property string $doc_file Документ
 * @property string $created_at
 *
 * @property CandidateCandidateTag[] $candidateCandidateTags
 * @property CandidateContact[] $candidateContacts
 * @property CandidateProjectStage[] $candidateProjectStages
 * @property Task[] $tasks
 */
class Candidate extends \yii\db\ActiveRecord
{
    /**
     * @var array
     */
    public $tags;

    /**
     * @var array
     */
    public $skills;

    /**
     * @var
     */
    public $files;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'candidate';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => null,
                'createdAtAttribute' => 'created_at',
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['comment', 'education', 'work_experience', 'languages', 'additional', 'doc_file'], 'string'],
            [['created_at', 'tags', 'skills', 'files'], 'safe'],
            ['email', 'email'],
            [['name', 'email', 'phone', 'city', 'age'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'ФИО',
            'email' => 'Email',
            'phone' => 'Телефон',
            'city' => 'Город',
            'comment' => 'Комментарий',
            'education' => 'Образование',
            'work_experience' => 'Опыт работы',
            'age' => 'Возраст',
            'languages' => 'Знание языков',
            'additional' => 'Дополнительная информация',
            'doc_file' => 'Документ',
            'tags' => 'Тэги',
            'skills' => 'Навыки',
            'created_at' => 'Дата и время создания',
        ];
    }



    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        CandidateCandidateTag::deleteAll(['candidate_id' => $this->id]);
        if($this->tags != null){
            foreach ($this->tags as $tag) {
                $candidateTag = CandidateTag::find()->where(['name' => $tag])->one();
                if($candidateTag == null){
                    $candidateTag = new CandidateTag(['name' => $tag]);
                    $candidateTag->save(false);
                }
                (new CandidateCandidateTag([
                    'candidate_id' => $this->id,
                    'candidate_tag_id' => $candidateTag->id,
                ]))->save(false);
            }
        }

        CandidateCandidateSkill::deleteAll(['candidate_id' => $this->id]);
        if($this->skills != null){
            foreach ($this->skills as $skill) {
                $candidateSkill = CandidateSkill::find()->where(['name' => $skill])->one();
                if($candidateSkill == null){
                    $candidateSkill = new CandidateSkill(['name' => $skill]);
                    $candidateSkill->save(false);
                }
                (new CandidateCandidateSkill([
                    'candidate_id' => $this->id,
                    'candidate_skill_id' => $candidateSkill->id,
                ]))->save(false);
            }
        }

        $files = explode(',', $this->files);

        foreach ($files as $file){
            if($file != null){
                $file = CandidateFile::findOne($file);
                $file->candidate_id = $this->id;
                $file->save(false);
            }
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateCandidateTags()
    {
        return $this->hasMany(CandidateCandidateTag::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateContacts()
    {
        return $this->hasMany(CandidateContact::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateProjectStages()
    {
        return $this->hasMany(CandidateProjectStage::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::className(), ['candidate_id' => 'id']);
    }
}

controllers/CandidateController.php
<?php

namespace app\controllers;

use app\components\helpers\TagHelper;
use app\models\CandidateEmail;
use app\models\CandidateEmailSearch;
use app\models\CandidateFile;
use app\models\CandidateFileSearch;
use app\models\CandidateProjectStep;
use app\models\CandidateSmsSearch;
use app\models\EmailTemplate;
use app\models\EmailTemplateSearch;
use app\models\forms\DocxForm;
use app\models\forms\EmailForm;
use app\models\forms\SmsForm;
use app\models\ProjectSearch;
use app\models\SmsTemplate;
use Yii;
use app\models\Candidate;
use app\models\CandidateSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * CandidateController implements the CRUD actions for Candidate model.
 */
class CandidateController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Candidate models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new CandidateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Candidate model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        $smsSearchModel = new CandidateSmsSearch();
        $smsDataProvider = $smsSearchModel->search([]);
        $smsDataProvider->query->andWhere(['candidate_id' => $id]);

        $emailSearchModel = new CandidateEmailSearch();
        $emailDataProvider = $emailSearchModel->search([]);
        $emailDataProvider->query->andWhere(['candidate_id' => $id]);

        $filesSearchModel = new CandidateFileSearch();
        $filesDataProvider = $filesSearchModel->search([]);
        $filesDataProvider->query->andWhere(['candidate_id' => $id]);

//        $projectSearchModel = new ProjectSearch();
//        $projectDataProvider = $projectSearchModel->search([]);
//        $projectsPks = CandidatePro
//        $projectDataProvider->query->andWhere(['candidate_id' => ]);

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "кандидат #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                        'smsSearchModel' => $smsSearchModel,
                        'smsDataProvider' => $smsDataProvider,
                        'emailSearchModel' => $emailSearchModel,
                        'emailDataProvider' => $emailDataProvider,
                        'filesSearchModel' => $filesSearchModel,
                        'filesDataProvider' => $filesDataProvider,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
                'smsSearchModel' => $smsSearchModel,
                'smsDataProvider' => $smsDataProvider,
                'emailSearchModel' => $emailSearchModel,
                'emailDataProvider' => $emailDataProvider,
                'filesSearchModel' => $filesSearchModel,
                'filesDataProvider' => $filesDataProvider,
            ]);
        }
    }

    /**
     * @param integer $candidateId
     * @param string $pjaxContainer
     * @return array
     */
    public function actionSendSms($candidateId, $pjaxContainer = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = new SmsForm([
            'candidateId' => $candidateId,
        ]);

        if($model->load($request->post()) && $model->send()){
            return [
                'forceReload' => $pjaxContainer,
                'title' => 'Отправить СМС',
                'content' => '<span class="text-success">СМС отправлено</span>',
                'footer' => Html::button('ОК',['class'=>'btn btn-default btn-block','data-dismiss'=>"modal"])
            ];
        } else {
            return [
                'title' => 'Отправить СМС',
                'content' => $this->renderAjax('send-sms', [
                    'model' => $model,
                    'candidateId' => $candidateId,
                ]),
                'footer' => Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]) .
                    Html::button('Отправить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }
    }

    public function actionGetSmsTemplateText($templateId, $candidateId)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $template = SmsTemplate::findOne($templateId);
        $candidate = Candidate::findOne($candidateId);

        if($candidate == null || $template == null){
            return ['error' => 'bad request'];
        }

        $message = TagHelper::handleModel($template->content, [$candidate]);

        return ['message' => $message];
    }

    public function actionDownloadFile($id)
    {
        $candidateFile = CandidateFile::findOne($id);

        if($candidateFile == null){
            throw new NotFoundHttpException();
        }

        if(file_exists($candidateFile->path)){
            Yii::$app->response->sendFile($candidateFile->path, $candidateFile->name);
        }
    }

    public function actionParseDocxFile()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = new DocxForm();

        if($request->isPost){

            $model->file = UploadedFile::getInstance($model, 'file');

            return $model->parse();
        }

        return ['error' => 1];
    }

    public function actionAddFile($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = $this->findModel($id);

        return [
            'title'=> "Добавить файлы",
            'content'=>$this->renderAjax('add_file', [
                'model' => $model,
            ]),
            'footer'=> Html::button('Готово',['class'=>'btn btn-default btn-block','data-dismiss'=>"modal"])
        ];
    }

    public function actionUploadFile($candidate_id = null)
    {
        $fileName = Yii::$app->security->generateRandomString();
        if(is_dir('uploads') == false){
            mkdir('uploads');
        }
        if(is_dir('uploads/data') == false){
            mkdir('uploads/data');
        }
        $uploadPath = 'uploads/data';

        if (isset($_FILES['file'])) {
            $file = \yii\web\UploadedFile::getInstanceByName('file');
            $path = $uploadPath.'/'.$fileName.'.'.$file->extension;

            if ($file->saveAs($path)) {
                //Now save file data to database
                $candidateFile = new CandidateFile([
                    'candidate_id' => $candidate_id,
                    'name' => $_FILES['file']['name'],
                    'path' => $path
                ]);
                $candidateFile->save(false);

                $file = (array) $file;
                $file['record'] = $candidateFile;

                echo \yii\helpers\Json::encode($file);
            }
        }

        return false;
    }


    /**
     * @param integer $id
     * @return array
     */
    public function actionSendEmail($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = new EmailForm([
            'candidateId' => $id,
        ]);

        if($model->load($request->post()) && $model->send()){
            return [
                'title' => 'Отправить Email',
                'content' => '<span class="text-success">сообщение отправлено</span>',
                'footer' => Html::button('ОК',['class'=>'btn btn-default btn-block','data-dismiss'=>"modal"])
            ];
        } else {
            return [
                'title' => 'Отправить Email',
                'content' => $this->renderAjax('send-email', [
                    'model' => $model,
                    'candidateId' => $id,
                ]),
                'footer' => Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]) .
                    Html::button('Отправить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }
    }

    public function actionGetEmailTemplateText($templateId, $candidateId)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $template = EmailTemplate::findOne($templateId);
        $candidate = Candidate::findOne($candidateId);

        if($candidate == null || $template == null){
            return ['error' => 'bad request'];
        }

        $message = TagHelper::handleModel($template->content, [$candidate]);

        return ['message' => $message];
    }

    /**
     * Creates a new Candidate model.

views/candidate/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
//    [
//        'class' => 'kartik\grid\CheckboxColumn',
//        'width' => '20px',
//    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($model){
            return Html::a($model->name, ['view', 'id' => $model->id], ['data-pjax' => '0']);
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'city',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'education',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'work_experience',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'age',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'languages',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'additional',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'doc_file',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
                return Url::to([$action,'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'contentOptions' => ['style' => 'white-space: nowrap;'],
        'buttons' => [
            'send-email' => function($url, $model) {
                return Html::a('<i class="fa fa-envelope text-success" style="font-size: 16px;"></i>', $url, ['role' => 'modal-remote']);
            },
            'send-sms' => function($url, $model) {
                return Html::a('<i class="fa fa-mobile text-success" style="font-size: 20px;"></i>', $url, ['role' => 'modal-remote']);
            },
            'view' => function($url, $model) {
                return Html::a('<i class="fa fa-eye" style="font-size: 16px;"></i>', $url, ['data-pjax' => '0']);
            },
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            }
        ],
    ],

];   

views/candidate/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \app\models\forms\DocxForm;

/* @var $this yii\web\View */
/* @var $model app\models\Candidate */
/* @var $form yii\widgets\ActiveForm */

if($model->isNewRecord == false) {
    $model->tags = \yii\helpers\ArrayHelper::getColumn(\app\models\CandidateCandidateTag::find()->where(['candidate_id' => $model->id])->all(), 'candidate_tag_id');
    $model->tags = \yii\helpers\ArrayHelper::getColumn(\app\models\CandidateTag::find()->where(['id' => $model->tags])->all(), 'name');
    $model->skills = \yii\helpers\ArrayHelper::getColumn(\app\models\CandidateCandidateSkill::find()->where(['candidate_id' => $model->id])->all(), 'candidate_skill_id');
    $model->skills = \yii\helpers\ArrayHelper::getColumn(\app\models\CandidateSkill::find()->where(['id' => $model->skills])->all(), 'name');
}


?>

<div class="candidate-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <?php $modelDocx = new DocxForm(); ?>
                    <?= $form->field($modelDocx, 'file')->fileInput()->label('Docx Файл') ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'age')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'tags')->widget(\kartik\select2\Select2::className(), [
                        'data' => \yii\helpers\ArrayHelper::map(\app\models\CandidateTag::find()->all(), 'name', 'name'),
                        'options' => [
                            'multiple' => true,
                        ],
                        'pluginOptions' => [
                            'tags' => true,
                            'tokenSeparators' => [','],
                        ],
                    ]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'skills')->widget(\kartik\select2\Select2::className(), [
                        'data' => \yii\helpers\ArrayHelper::map(\app\models\CandidateSkill::find()->all(), 'name', 'name'),
                        'options' => [
                            'multiple' => true,
                        ],
                        'pluginOptions' => [
                            'tags' => true,
                            'tokenSeparators' => [','],
                        ],
                    ]) ?>
                </div>
            </div>


            <div class="row">
                <div class="col-md-12">
                    <?php if($model->isNewRecord): ?>
                        <?= \kato\DropZone::widget([
                            'id'        => 'dzImage', // <-- уникальные id
                            'uploadUrl' => \yii\helpers\Url::toRoute([ 'upload-file' ]),
                            'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
                            'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
                            'options' => [
                                'maxFilesize' => '2',
                            ],
                            'clientEvents' => [
                                'success' => "function(file, response){ 
                                response = JSON.parse(response);
                                   
                                var id = response.record.id;
                                
                                var value = $('#candidate-files').val();
                                $('#candidate-files').val(value+','+id);
                             }",
                                'complete' => "function(file){ console.log(file); }",
                            ],
                        ]);?>
                    <?php else: ?>
                        <?= \kato\DropZone::widget([
                            'id'        => 'dzImage', // <-- уникальные id
                            'uploadUrl' => \yii\helpers\Url::toRoute([ 'upload-file', 'candidate_id' => $model->id]),
                            'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
                            'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
                            'options' => [
                                'maxFilesize' => '2',
                            ],
                        ]);?>
                    <?php endif; ?>
                </div>
            </div>

            <div class="hidden">
                <?= $form->field($model, 'files')->hiddenInput() ?>
            </div>

        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'education')->textarea(['rows' => 6]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'work_experience')->textarea(['rows' => 6]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'languages')->textarea(['rows' => 6]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'additional')->textarea(['rows' => 6]) ?>
                </div>
            </div>
        </div>

    </div>



	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>

</div>


<?php

$script = <<< JS
$('#docxform-file').change(function(){
    var file = $('#docxform-file').prop('files')[0];
    var formData = new FormData();
    formData.append('DocxForm[file]', file);
    $.ajax({
        method: "POST",
        url: '/candidate/parse-docx-file',
        data: formData,
        processData: false,
        contentType: false,
        success: function(response){
            $('#candidate-name').val(response.name);
            $('#candidate-work_experience').val(response.work);
            $('#candidate-age').val(response.age);
            $('#candidate-phone').val(response.phone);
            $('#candidate-education').val(response.education);
            $('#candidate-email').val(response.email);
            $('#candidate-additional').val(response.additional);
            for(var i = 0; i < response.skills.length; i++)
            {
                console.log(response.skills[i]);
                var option = new Option(response.skills[i], response.skills[i], false, true);
                $('#candidate-skills').append(option).trigger('change');
            }
        }
    });
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/candidate/_search.php
<?php
use kartik\typeahead\TypeaheadBasic;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \app\models\forms\DocxForm;

/* @var $this yii\web\View */
/* @var $model app\models\CandidateSearch */
/* @var $form yii\widgets\ActiveForm */
/* @var $data \app\models\Candidate[] */

$data = \yii\helpers\ArrayHelper::getColumn($data, 'name');

?>

    <div class="candidate-form pull-right" style="display: inline-block; margin-top: -4px; width: 25%;">

        <?php $form = ActiveForm::begin(['id' => 'search-form', 'method' => 'GET']); ?>

        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'name')->widget(TypeaheadBasic::className(), [
                    'data' => $data,
                    'options' => [
                        'placeholder' => 'Поиск',
                        'autocomplete' => 'off',
                    ],
                ])->label(false) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>


<?php
$script = <<< JS

$('#candidatesearch-name').change(function(){
    $('#search-form').submit();
});

JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/candidate/add_file.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \app\models\forms\DocxForm;

/* @var $this yii\web\View */
/* @var $model app\models\Candidate */
/* @var $form yii\widgets\ActiveForm */


?>

    <div class="candidate-form">

        <?php $form = ActiveForm::begin(); ?>

                <div class="row">
                    <div class="col-md-12">

                            <?= \kato\DropZone::widget([
                                'id'        => 'dzImage', // <-- уникальные id
                                'uploadUrl' => \yii\helpers\Url::toRoute([ 'upload-file', 'candidate_id' => $model->id]),
                                'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
                                'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
                                'options' => [
                                    'maxFilesize' => '2',
                                ],
                                'clientEvents' => [
                                    'success' => "function(file, response){ 
                                        $.pjax.reload('#crud-file-datatable-pjax');                                    
                                    }",
                                ],
                            ]);?>
                    </div>
                </div>



        <?php ActiveForm::end(); ?>

    </div>

views/candidate/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Candidate */

?>
<div class="candidate-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/candidate/send-email.php
<?php

use yii\widgets\ActiveForm;

/**
 * @var \app\models\forms\SmsForm $model
 */

?>

<?php $form = ActiveForm::begin() ?>

<div class="row">
    <div class="col-md-12">
        <?= $form->field($model, 'templateId')->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\EmailTemplate::find()->all(), 'id', 'name')) ?>
    </div>
</div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'message')->widget(\mihaildev\ckeditor\CKEditor::className(), [
                'editorOptions' => [
                    'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                ]
            ]) ?>
        </div>
    </div>

<?php ActiveForm::end() ?>



<?php

$script = <<< JS

$('#emailform-templateid').change(function(){
    var templateId = $(this).val();
    $.ajax({
        url: '/candidate/get-email-template-text?candidateId={$candidateId}&templateId='+templateId,
        method: 'GET',
        success: function(response){
            if(response.message != undefined){
                CKEDITOR.instances['emailform-message'].setData(response.message);
            }
        }
    });
});

JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/candidate/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Candidate */
?>
<div class="candidate-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>